theme: jekyll-theme-minimal
title: Advances and Challenges
email: elisabetta.ronchieri@cnaf.infn.it
description: The 26th International Conference of the Society of Design and Process Science on Advances and Challenges of Applying AI/GenAI in Design and Process Science (GenAI4DPS 2024) holds on October 6-9, Bologna, Italy. 
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: ai, generative model, large language model, natural language processing

lang: en

url: https://genai4dps.github.io
baseurl: /advances-challenges
last_updated: true

navbar_fixed: true
footer_fixed: false

max_width: 875px
