theme: jekyll-theme-minimal
title: Advances and Challenges
email: elisabetta.ronchieri@cnaf.infn.it
description: Bookmark this to keep an eye on my project updates!

lang: en

url: https://GenAI4DPS.github.io
baseurl: /advances-challenges
last_updated: true

