# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

#theme: jekyll-theme-minimal
title: Advances and Challenges
email: elisabetta.ronchieri@cnaf.infn.it
description: The 26th International Conference of the Society of Design and Process Science on Advances and Challenges of Applying AI/GenAI in Design and Process Science (GenAI4DPS 2024) holds on October 6-9, Bologna, Italy. 
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: ai, generative model, large language model, natural language processing

lang: en

url: https://genai4dps.github.io
baseurl: /advances-challenges
last_updated: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# code highlighter theme
highlight_theme_light: github   # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native    # https://github.com/jwarby/jekyll-pygments-themes

# repo color theme
repo_theme_light: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat    # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed  # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: false

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false

# Dimensions
max_width: 875px #80%

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/

announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the `_news` folder

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
