theme: jekyll-theme-minimal
title: Advances and Challenges
email: elisabetta.ronchieri@cnaf.infn.it
description: 

lang: en

url: https://genai4dps.github.io
baseurl: /advances-challenges
last_updated: true

navbar_fixed: true
footer_fixed: false

max_width: 875px
